# Generated by Django 5.2.7 on 2025-10-23 11:57

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ICP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("industry", models.CharField(max_length=255)),
                ("location", models.CharField(blank=True, max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("company", models.CharField(max_length=255)),
                ("website", models.URLField(blank=True, null=True)),
                ("linkedin_url", models.URLField(blank=True, null=True)),
                ("verified", models.BooleanField(default=False)),
                ("personalization_note", models.TextField(blank=True, null=True)),
                ("intent_score", models.FloatField(default=0)),
                ("fit_score", models.FloatField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=7, max_length=20, prefix="", unique=True
                    ),
                ),
                (
                    "icp",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outbound.icp"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=7, max_length=20, prefix="", unique=True
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outbound.lead"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NurtureSequence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence_stage", models.IntegerField()),
                ("message_text", models.TextField()),
                ("completed", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outbound.lead"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_text", models.TextField()),
                (
                    "stage",
                    models.CharField(
                        choices=[
                            ("first_touch", "First Touch"),
                            ("follow_up", "Follow Up"),
                            ("nurture", "Nurture"),
                        ],
                        max_length=50,
                    ),
                ),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outbound.campaign",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="outbound.lead"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ResponseTracking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("open_status", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
                ("response_text", models.TextField(blank=True, null=True)),
                ("response_time", models.DateTimeField(blank=True, null=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="outbound.outboundmessage",
                    ),
                ),
            ],
        ),
    ]
