# Generated by Django 5.2.7 on 2025-10-23 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="company",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
