# Generated by Django 5.2.7 on 2025-10-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0002_alter_lead_company_alter_lead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="source",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
