# Generated by Django 5.2.7 on 2025-10-24 11:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0003_lead_source"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="icp",
        ),
    ]
