# Generated by Django 5.2.7 on 2025-10-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0004_remove_lead_icp"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="note",
            field=models.TextField(blank=True, null=True),
        ),
    ]
