# Generated by Django 5.2.7 on 2025-10-24 14:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0005_lead_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
