# Generated by Django 5.2.7 on 2025-10-24 16:20

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0006_lead_address"),
    ]

    operations = [
        migrations.CreateModel(
            name="VerifiedLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=50, null=True)),
                ("company", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "lead_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=7, max_length=20, prefix="", unique=True
                    ),
                ),
                ("source", models.CharField(blank=True, max_length=50, null=True)),
                ("personalization_note", models.TextField(blank=True, null=True)),
                ("intent_score", models.FloatField(default=0)),
                ("fit_score", models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name="lead",
            name="personalization_note",
        ),
    ]
