# Generated by Django 5.2.7 on 2025-10-24 17:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0007_verifiedlead_remove_lead_personalization_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedlead",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
