# Generated by Django 5.2.7 on 2025-10-25 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0008_verifiedlead_website"),
    ]

    operations = [
        migrations.AddField(
            model_name="verifiedlead",
            name="opened",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verifiedlead",
            name="replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verifiedlead",
            name="stage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("first_touch", "First Touch"),
                    ("follow_up", "Follow Up"),
                    ("nurture", "Nurture"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
