# Generated by Django 5.2.7 on 2025-10-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0009_verifiedlead_opened_verifiedlead_replied_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="outboundmessage",
            name="campaign",
        ),
        migrations.RemoveField(
            model_name="outboundmessage",
            name="message_text",
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="body",
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="subject_line",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="verifiedlead",
            name="date_sent",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verifiedlead",
            name="email_provider_used",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verifiedlead",
            name="opened_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="verifiedlead",
            name="sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="verifiedlead",
            name="total_email_sent",
            field=models.FloatField(default=0),
        ),
    ]
