# Generated by Django 5.2.7 on 2025-10-25 14:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0010_remove_outboundmessage_campaign_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="outboundmessage",
            name="lead",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="outbound.verifiedlead"
            ),
        ),
    ]
