# Generated by Django 5.2.7 on 2025-11-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0011_alter_outboundmessage_lead"),
    ]

    operations = [
        migrations.CreateModel(
            name="WebsiteLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("email", models.CharField(max_length=255)),
                ("company_name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
