# Generated by Django 5.2.7 on 2026-01-03 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("outbound", "0012_websitelead"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("prompt", models.TextField()),
                ("subject", models.CharField(blank=True, max_length=255, null=True)),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="nurturesequence",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="outboundmessage",
            name="lead",
        ),
        migrations.RemoveField(
            model_name="responsetracking",
            name="message",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="verified",
            new_name="bounce",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="linkedin_url",
            new_name="company_linkedin",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="address",
            new_name="country",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="phone",
            new_name="email_provider_used",
        ),
        migrations.RenameField(
            model_name="lead",
            old_name="note",
            new_name="keywords",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="fit_score",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="intent_score",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="lead_id",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="name",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="source",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="lead",
            name="departments",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_status",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="employees",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="first_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="followup_sent",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="industry",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="intent",
            field=models.CharField(
                choices=[
                    ("HIGH", "High Intent (Agency / Consultancy)"),
                    ("MEDIUM", "Medium Intent (Service Business)"),
                    ("LOW", "Low Intent (Weak Fit)"),
                    ("REJECTED", "Rejected / Non-ICP"),
                ],
                db_index=True,
                default="REJECTED",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_contacted",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="last_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="person_linkedin",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="processing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="ready_to_send",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="replied",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="score",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="lead",
            name="score_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="seniority",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="seo_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="technologies",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name="LeadEmailCopy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("template_name", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=255)),
                ("body", models.TextField()),
                ("ready_to_send", models.BooleanField(default=False)),
                ("sent", models.BooleanField(default=False)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("opened", models.BooleanField(default=False)),
                ("clicked", models.BooleanField(default=False)),
                ("replied", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_copies",
                        to="outbound.lead",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lead Email Copy",
                "verbose_name_plural": "Lead Email Copies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="Campaign",
        ),
        migrations.DeleteModel(
            name="NurtureSequence",
        ),
        migrations.DeleteModel(
            name="VerifiedLead",
        ),
        migrations.DeleteModel(
            name="OutboundMessage",
        ),
        migrations.DeleteModel(
            name="ResponseTracking",
        ),
    ]
